import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/Components/navbar/Navbar'
import Footer from '@/Components/footer/Footer'
import { ThemeProvider } from "@/Context/ThemeContext";
import AuthProvider from "@/Components/AuthProvider/AuthProvider";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
        <AuthProvider>
          <div className='container'>
            <Navbar />
            {children}
            <Footer />
          </div>
        </AuthProvider>
        </ThemeProvider>
        
      </body>
</html>
  )
}

/*
<body className={inter.className}>
  <Navbar />
  {children}
  <Footer />
</body>*/
